/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Do_an;

import static Do_an.KetNoi.layKetNoi;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class KhachHang extends javax.swing.JFrame {

    String username = "";
    Random rand = new Random();
    //int Mave = rand.nextInt(100000) + 1;

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
        layTram();
        layTuyen();
        SoXe.setText(laySoXe(username));
        //   LaythoiGian();
        this.setLocationRelativeTo(null);
        this.setTitle("Bán vé");
    }

    public KhachHang(String user) {
        initComponents();
        layTram();
        layTuyen();
        // LaythoiGian();
        username = user;
        SoXe.setText(laySoXe(username));
        this.setLocationRelativeTo(null);
        this.setTitle("Bán vé");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_sv = new javax.swing.JButton();
        btn_hanhkhach = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Com_Tram = new javax.swing.JComboBox<>();
        Com_Tuyen = new javax.swing.JComboBox<>();
        SoXe = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BÁN VÉ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 250, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 540, 10));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TRẠM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, 50));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TUYẾN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 110, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SỐ XE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 130, 50));

        btn_back.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(58, 71, 80));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/back_18.png"))); // NOI18N
        btn_back.setText("TRỞ VỀ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, 120, 40));

        btn_sv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_sv.setForeground(new java.awt.Color(58, 71, 80));
        btn_sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/student_22.png"))); // NOI18N
        btn_sv.setText("HS/SV");
        btn_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_svActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 110, 40));

        btn_hanhkhach.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_hanhkhach.setForeground(new java.awt.Color(58, 71, 80));
        btn_hanhkhach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/people_22.png"))); // NOI18N
        btn_hanhkhach.setText("HÀNH KHÁCH");
        btn_hanhkhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hanhkhachActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hanhkhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 160, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/ticket_50.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, 50));

        Com_Tram.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Com_Tram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Com_TramActionPerformed(evt);
            }
        });
        jPanel1.add(Com_Tram, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 310, 40));

        Com_Tuyen.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(Com_Tuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 310, 40));

        SoXe.setBackground(new java.awt.Color(153, 153, 153));
        SoXe.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        SoXe.setOpaque(true);
        jPanel1.add(SoXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 310, 40));

        jLabel10.setBackground(new java.awt.Color(183, 183, 183));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/bg_form.jpg"))); // NOI18N
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void Com_TramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Com_TramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Com_TramActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        User st = new User(username);
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_hanhkhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hanhkhachActionPerformed
        String a = Com_Tram.getSelectedItem().toString();
        String b = Com_Tuyen.getSelectedItem().toString();
        String c = SoXe.getText();

        String gio = LayGio();
        int d = 7000;
        int maloai = 2;
        int Mave = LayMaVe(maloai);
        
        ThongTinVe tt = new ThongTinVe(a, b, c, d, Mave, gio);
        themduLieuVe(Mave, layMaChuyenXe(c), gio, maloai, layMatram(a));

        tt.setVisible(true);
    }//GEN-LAST:event_btn_hanhkhachActionPerformed

    private void btn_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_svActionPerformed
        String a = Com_Tram.getSelectedItem().toString();
        String b = Com_Tuyen.getSelectedItem().toString();
        String c = SoXe.getText();
        int d = 3000;
        int maloai = 1;
        int Mave = LayMaVe(maloai);
        String gio = LayGio();

        ThongTinVe tt = new ThongTinVe(a, b, c, d, Mave, gio);
        themduLieuVe(Mave, layMaChuyenXe(c), gio, maloai, layMatram(a));

        tt.setVisible(true);
    }//GEN-LAST:event_btn_svActionPerformed

    public String LayNgay() {
        String a;
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        SimpleDateFormat ngay = new SimpleDateFormat("yyyy/MM/dd");
        a = ngay.format(date);
        return a;
    }

    public String LayGio() {
        String a;
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        SimpleDateFormat gio = new SimpleDateFormat("HH:mm:ss");
        a = gio.format(date);
        return a;
    }

    public void layTram() {
        Connection kn = layKetNoi();
        String Sql = "Select TenTram from TRAM ORDER BY MaTram";
        try {
            PreparedStatement ps = kn.prepareStatement(Sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Com_Tram.addItem(rs.getString("TenTram"));
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);

        }

    }

    public void layTuyen() {
        Connection kn = layKetNoi();
        String Sql = "Select DISTINCT TuyenXe from XE";
        try {
            PreparedStatement ps = kn.prepareStatement(Sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Com_Tuyen.addItem(rs.getString("TuyenXe"));
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);

        }

    }

    public String layMaNV(String tk) {
        String manv = "";
        String sql = "select MaNV from NHANVIEN where TAIKHOAN = ?";
        Connection kn = layKetNoi();
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ps.setString(1, tk);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                manv = rs.getString("MaNV");
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);

        }

        return manv;
    }

    public String laySoXe(String tk) {
        String soxe = "";
        Connection kn = layKetNoi();
        String Sql = "select BienSoXe \n"
                + "from NHANVIEN, CHUYENXE\n"
                + "where NHANVIEN.MaNV = CHUYENXE.MaNV\n"
                + "and NHANVIEN.MaNV=?\n"
                + "and NgayChay = ?";
        try {
            PreparedStatement ps = kn.prepareStatement(Sql);
            ps.setString(1, layMaNV(tk));
            ps.setString(2, LayNgay());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                soxe = rs.getString(1);
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);
        }
        return soxe;

    }

    public void themduLieuVe(int mave, int maxe, String thoigian,
            int maloai, int matram) {
        Connection kn = layKetNoi();
        String sql = "insert into VEXE values (?,?,?,?,?)";
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ps.setInt(1, mave);
            ps.setInt(2, maxe);
            ps.setString(3, thoigian);
            ps.setInt(4, maloai);
            ps.setInt(5, matram);
            ps.executeUpdate();
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    public int layMatram(String tram) {
        int matram = 0;
        Connection kn = layKetNoi();
        String Sql = "Select * from TRAM ";
        try {
            PreparedStatement ps = kn.prepareStatement(Sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                if (rs.getString("TenTram").equals(tram)) {
                    matram = rs.getInt("MaTram");
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);

        }
        return matram;
    }

    public int layMaChuyenXe(String biensoXe) {
        int machuyenxe = 0;
        Connection kn = layKetNoi();
        String Sql = "Select * from CHUYENXE ";
        try {
            PreparedStatement ps = kn.prepareStatement(Sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                if (rs.getString("BienSoXe").equals(biensoXe)) {
                    machuyenxe = rs.getInt("MaChuyenXe");
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);
        }
        return machuyenxe;
    }

    public int SlChuyenXe() {
        int a = 0;
        Connection kn = layKetNoi();
        String Sql = "select COUNT(MaChuyenXe) from CHUYENXE";
        try {
            PreparedStatement ps = kn.prepareStatement(Sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                a = rs.getInt(1);
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);

        }
        return a;
    }

    public int LayMaVe(int maloai) {
        int mave = 0;
        String a = null;
        String c = SoXe.getText();
        Connection kn = layKetNoi();

        String sql = "SELECT MAX(Mave) FROM VEXE,CHUYENXE where MaLoaiVe = ? \n"
                + "and VEXE.MaChuyenXe=CHUYENXE.MaChuyenXe\n"
                + "and CHUYENXE.MaChuyenXe= ? ";
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ps.setInt(1, maloai);
            ps.setInt(2, layMaChuyenXe(SoXe.getText()));
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                mave = rs.getInt(1);
            }
        } catch (SQLException e) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, e);
        }

        if (maloai == 1 && mave == 0) {
            mave = 0;
        }

        if (maloai == 2 && mave == 0) {
            mave = 5000;
        }
        
        String ChMave;
        if (mave == 0 || mave == 5000) {
            if (mave == 0) {
                ChMave = layMaChuyenXe(c) + "000" + mave;
                mave = Integer.parseInt(ChMave);

            } else {
                ChMave = layMaChuyenXe(c) + "" + mave;
                mave = Integer.parseInt(ChMave);
            }
        }

        mave = mave + 1;

        return mave;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Com_Tram;
    private javax.swing.JComboBox<String> Com_Tuyen;
    private javax.swing.JLabel SoXe;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_hanhkhach;
    private javax.swing.JButton btn_sv;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
