/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Do_an;

import static Do_an.KetNoi.layKetNoi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class LayLaiMK extends javax.swing.JFrame {

    /**
     * Creates new form LayLaiMK
     */
    public LayLaiMK() {
        initComponents();
        layTaiKhoan();
        this.setTitle("Lấy lại mật khẩu");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        B_Oke = new javax.swing.JButton();
        B_Back = new javax.swing.JButton();
        T_Pass1 = new javax.swing.JPasswordField();
        T_Pass2 = new javax.swing.JPasswordField();
        Com_TK = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LẤY LẠI MẬT KHẨU");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 350, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 540, 10));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TÊN TÀI KHOẢN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, 50));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MẬT KHẨU MỚI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 150, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NHẬP LẠI MẬT KHẨU");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 170, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/key_50.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 50));

        B_Oke.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_Oke.setForeground(new java.awt.Color(58, 71, 80));
        B_Oke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/oke_22.png"))); // NOI18N
        B_Oke.setText("XONG");
        B_Oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_OkeActionPerformed(evt);
            }
        });
        jPanel1.add(B_Oke, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 110, 40));

        B_Back.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_Back.setForeground(new java.awt.Color(58, 71, 80));
        B_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/back_18.png"))); // NOI18N
        B_Back.setText("TRỞ VỀ");
        B_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BackActionPerformed(evt);
            }
        });
        jPanel1.add(B_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 120, 40));

        T_Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_Pass1ActionPerformed(evt);
            }
        });
        jPanel1.add(T_Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 310, 40));
        jPanel1.add(T_Pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 310, 40));

        Com_TK.setBackground(new java.awt.Color(204, 204, 204));
        Com_TK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(Com_TK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 310, 40));

        jLabel10.setBackground(new java.awt.Color(183, 183, 183));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/bg_form.jpg"))); // NOI18N
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_OkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_OkeActionPerformed
        String ten = Com_TK.getSelectedItem().toString();
        String pass = T_Pass1.getText();
        String pass2 = T_Pass2.getText();
        
        if(!pass.equals(""))
        {
            if(checkpass(pass) == 1)
            {
                if(!pass2.equals(""))
                {
                    if(pass2.equals(pass))   
                    {
                        Sua(pass,ten);
                        JOptionPane.showMessageDialog(rootPane, "Lấy lại mật khẩu thành công");
                        Admin ad = new Admin();
                        ad.setVisible(true);
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Mật khẩu nhập không khớp", "Thông Báo", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Vui lòng không để trống mật khẩu", "Thông Báo", JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu đúng định dạng ký tự (a-z,A-Z,0-9)", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống mật khẩu", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        }
         
    }//GEN-LAST:event_B_OkeActionPerformed

    private void B_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BackActionPerformed
        Admin ad = new Admin();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B_BackActionPerformed

    private void T_Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_Pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_Pass1ActionPerformed

    public void Sua(String MK, String TK) {
        Connection kn = layKetNoi();
        String sql = "update TAIKHOAN set MatKhau =? Where TaiKhoan=?";
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            
            ps.setString(1, MK);
            ps.setString(2, TK);
            
            ps.executeUpdate();
        } catch (SQLException e) {
            Logger.getLogger(editNhanVien.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void layTaiKhoan() {
        Connection kn = layKetNoi();
        String Sql = "select TaiKhoan from NHANVIEN";
        try {
            PreparedStatement ps = kn.prepareStatement(Sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Com_TK.addItem(rs.getString("TaiKhoan"));
            }
        } catch (SQLException e) {
            Logger.getLogger(TongKetVeNgay.class.getName()).log(Level.SEVERE, null, e);

        }
    }
    
    public int checkpass(String a) {
        int b = 0;
        String check = "[a-zA-Z0-9]{1,20}$";
        if (a.matches(check)) {
            b = 1;
        }
        return b;
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayLaiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Back;
    private javax.swing.JButton B_Oke;
    private javax.swing.JComboBox<String> Com_TK;
    private javax.swing.JPasswordField T_Pass1;
    private javax.swing.JPasswordField T_Pass2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
