package Do_an;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Do_an.KetNoi.layKetNoi;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setTitle("Đăng nhập");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Text_User1 = new javax.swing.JTextField();
        Text_Pass1 = new javax.swing.JPasswordField();
        B_DangNhap = new javax.swing.JButton();
        B_Reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("ĐĂNG NHẬP");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 214, 49));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/user.png"))); // NOI18N
        jLabel28.setToolTipText("");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/key.png"))); // NOI18N
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 470, 10));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TÀI KHOẢN");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 140, 40));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("MẬT KHẨU");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 140, 40));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/bus.png"))); // NOI18N
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 164));

        jLabel33.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("BUS 55");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, 44));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("QUẢN LÝ VÉ");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 196, 58));

        Text_User1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(Text_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 247, 35));

        Text_Pass1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Pass1ActionPerformed(evt);
            }
        });
        Text_Pass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_Pass1KeyPressed(evt);
            }
        });
        jPanel4.add(Text_Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 250, 35));

        B_DangNhap.setBackground(new java.awt.Color(51, 153, 255));
        B_DangNhap.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        B_DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        B_DangNhap.setText("Đăng nhập");
        B_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DangNhapActionPerformed(evt);
            }
        });
        jPanel4.add(B_DangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 156, 44));

        B_Reset.setBackground(new java.awt.Color(51, 153, 255));
        B_Reset.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        B_Reset.setForeground(new java.awt.Color(255, 255, 255));
        B_Reset.setText("Reset");
        B_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ResetActionPerformed(evt);
            }
        });
        jPanel4.add(B_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 650, 156, 44));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/bg_login.jpg"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void B_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DangNhapActionPerformed
        // TODO add your handling code here:
        String ten = Text_User1.getText().toUpperCase().trim();
        String pass = Text_Pass1.getText();
        int a = 2;
        int b = 1;

        Connection kn = layKetNoi();
        String sql = "Select * from TAIKHOAN WHERE TaiKhoan =? AND MatKhau =?";

        if (ten.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Điền Đầy Đủ Thông tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                PreparedStatement ps = kn.prepareStatement(sql);
                ps.setString(1, ten);
                ps.setString(2, pass);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    if (rs.getInt("MaVaiTro") == a) {
                        Admin ad = new Admin(ten);
                        ad.setVisible(true);
                        this.dispose();
                    } else if (rs.getInt("MaVaiTro") == b) {
                        User use = new User(ten);
                        use.setVisible(true);
                        this.dispose();
                    }
                } else if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "Tài Khoản Hoặc Mật Khẩu Không Đúng", "Thông Báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
            }
        }


    }//GEN-LAST:event_B_DangNhapActionPerformed

    private void B_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ResetActionPerformed
        // TODO add your handling code here:
        Text_Pass1.setText("");
        Text_User1.setText("");


    }//GEN-LAST:event_B_ResetActionPerformed

    private void Text_Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Pass1ActionPerformed

    private void Text_Pass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_Pass1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String ten = Text_User1.getText().toUpperCase().trim();
            String pass = Text_Pass1.getText();
            int a = 2;
            int b = 1;

            Connection kn = layKetNoi();
            String sql = "Select * from TAIKHOAN WHERE TaiKhoan =? AND MatKhau =?";

            if (ten.equals("") || pass.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui Lòng Điền Đầy Đủ Thông tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    PreparedStatement ps = kn.prepareStatement(sql);
                    ps.setString(1, ten);
                    ps.setString(2, pass);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        if (rs.getInt("MaVaiTro") == a) {
                            Admin ad = new Admin(ten);
                            ad.setVisible(true);
                            this.dispose();
                        } else if (rs.getInt("MaVaiTro") == b) {
                            User use = new User(ten);
                            use.setVisible(true);
                            this.dispose();
                        }
                    } else if (rs.next() == false) {
                        JOptionPane.showMessageDialog(this, "Tài Khoản Hoặc Mật Khẩu Không Đúng", "Thông Báo", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException e) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
                }
            }

        }

    }//GEN-LAST:event_Text_Pass1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_DangNhap;
    private javax.swing.JButton B_Reset;
    private javax.swing.JPasswordField Text_Pass1;
    private javax.swing.JTextField Text_User1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
