/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Do_an;

import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ThongTinVe extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinVe
     */
    public ThongTinVe() {
        initComponents();
        this.setLocationRelativeTo(null);
        LaythoiGian();
        this.setTitle("Thông tin vé");

    }

    public ThongTinVe(String tram, String tuyen, String soxe, int gia, int mave,String gio) {
        initComponents();
        this.L_Tram.setText(tram);
        this.L_Tuyen.setText(tuyen);
        this.L_SoXe.setText(soxe);
        this.L_Gia.setText(gia+"");
        this.L_MaVe.setText(mave+"");
        LaythoiGian();
        this.L_Gio.setText(gio);
        this.setTitle("Thông tin vé");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        L_Gio = new javax.swing.JLabel();
        L_SoXe = new javax.swing.JLabel();
        L_ngay = new javax.swing.JLabel();
        L_Tuyen = new javax.swing.JLabel();
        L_Tram = new javax.swing.JLabel();
        L_MaVe = new javax.swing.JLabel();
        L_Gia = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 750));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel16.setText("Công ty Cổ Phần Xe Khách ABC");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 410, 50));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Giá vé");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel18.setText("97 Đường Man Thiện, Hiệp Phú, Quận 9, Thành phố Hồ Chí Minh");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 590, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 100, 620, 10));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Đồng/ lượt");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel20.setText("Vé Xe Buýt");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Tên Trạm");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel22.setText("(Liên 2: Hành Khách Xin giữ vé để kiểm soát)");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("Giờ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("In Tại Phần Mềm Nhóm 19");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("Ngày");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("SĐT");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, 37, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("Mã số tuyến");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 95, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("00000000000");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("Số Xe");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 110, 40));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("Mã vé");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        L_Gio.setBackground(new java.awt.Color(204, 223, 235));
        L_Gio.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        L_Gio.setText(" ");
        L_Gio.setOpaque(true);
        jPanel1.add(L_Gio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, 40));

        L_SoXe.setBackground(new java.awt.Color(204, 223, 235));
        L_SoXe.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        L_SoXe.setOpaque(true);
        jPanel1.add(L_SoXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 110, 40));

        L_ngay.setBackground(new java.awt.Color(204, 223, 235));
        L_ngay.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        L_ngay.setText(" ");
        L_ngay.setOpaque(true);
        jPanel1.add(L_ngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 110, 40));

        L_Tuyen.setBackground(new java.awt.Color(204, 223, 235));
        L_Tuyen.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        L_Tuyen.setText(" ");
        L_Tuyen.setOpaque(true);
        jPanel1.add(L_Tuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 110, 40));

        L_Tram.setBackground(new java.awt.Color(204, 223, 235));
        L_Tram.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        L_Tram.setOpaque(true);
        jPanel1.add(L_Tram, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 260, 40));

        L_MaVe.setBackground(new java.awt.Color(204, 223, 235));
        L_MaVe.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        L_MaVe.setOpaque(true);
        jPanel1.add(L_MaVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 110, 40));

        L_Gia.setBackground(new java.awt.Color(204, 223, 235));
        L_Gia.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        L_Gia.setText(" ");
        L_Gia.setOpaque(true);
        jPanel1.add(L_Gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 80, 50));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/bg_vexe2.jpg"))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JOptionPane.showMessageDialog(rootPane, "Mua vé thành công");
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void LaythoiGian() {
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        SimpleDateFormat ngay = new SimpleDateFormat("dd/MM/yyyy");
        L_ngay.setText(ngay.format(date));
       // SimpleDateFormat gio = new SimpleDateFormat("HH:mm:ss");
       // L_Gio.setText(gio.format(date));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Gia;
    private javax.swing.JLabel L_Gio;
    private javax.swing.JLabel L_MaVe;
    private javax.swing.JLabel L_SoXe;
    private javax.swing.JLabel L_Tram;
    private javax.swing.JLabel L_Tuyen;
    private javax.swing.JLabel L_ngay;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
