/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Do_an;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Do_an.KetNoi.layKetNoi;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Administrator
 */
public class TongKetVeNgay extends javax.swing.JFrame {

    /**
     * Creates new form TongKetVe
     */
    public TongKetVeNgay() {
        
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        SimpleDateFormat ngay = new SimpleDateFormat("dd");
        SimpleDateFormat thang = new SimpleDateFormat("MM");
        SimpleDateFormat nam = new SimpleDateFormat("yyyy");
        initComponents();
        L_GiaSV.setText("");
        L_SLSV.setText("");
        L_TKSV.setText("");
        L_GiaTh.setText("");
        L_SLT.setText("");
        L_TKT.setText("");
        Tong.setText("");

        N_Ngay.setMaximum(31);
        N_Ngay.setMinimum(1);
        N_Thang.setMaximum(12);
        N_Thang.setMinimum(1);
        N_Nam.setMaximum(2100);
        N_Nam.setMinimum(2000);

        N_Ngay.setValue(Integer.parseInt(ngay.format(date)));
        N_Thang.setValue(Integer.parseInt(thang.format(date)));
        N_Nam.setValue(Integer.parseInt(nam.format(date)));

        SinhVien();
        Thuong();
        Tong();
        this.setLocationRelativeTo(null);
        this.setTitle("Tổng kết vé theo ngày");

    }

    public String laysoluong(String maloai, String ngay) {
        String a = "";
        Connection kn = layKetNoi();
        String sql = "select COUNT(MaVe) from VEXE,CHUYENXE "
                + "where CHUYENXE.MaChuyenXe=VEXE.MaChuyenXe "
                + "and VEXE.MaLoaiVe=? "
                + "and CHUYENXE.NgayChay= ?";

        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ps.setString(1, maloai);
            ps.setString(2, ngay);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                a = rs.getString(1);
            }
        } catch (SQLException e) {
            Logger.getLogger(TongKetVeNgay.class.getName()).log(Level.SEVERE, null, e);
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        B_HienThi1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        N_Ngay = new com.toedter.components.JSpinField();
        N_Thang = new com.toedter.components.JSpinField();
        N_Nam = new com.toedter.components.JSpinField();
        L_GiaSV = new javax.swing.JLabel();
        L_SLSV = new javax.swing.JLabel();
        L_TKSV = new javax.swing.JLabel();
        L_GiaTh = new javax.swing.JLabel();
        L_SLT = new javax.swing.JLabel();
        L_TKT = new javax.swing.JLabel();
        Tong = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Loại Vé");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Số Lượng Bán Ra");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 106, 32));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Giá Tiền");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 70, 24));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Số Tiền Thu Được");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Học Sinh/ Sinh Viên");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Thường");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel23.setText("TỔNG KẾT VÉ THEO NGÀY");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 50));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel24.setText("Tổng Tiền Thu Được:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("Loại Vé");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("Số Lượng Bán Ra");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 106, 32));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/back_18.png"))); // NOI18N
        jButton2.setText("Quay về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 120, 40));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("Giá Tiền");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, 24));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("Số Tiền Thu Được");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        B_HienThi1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        B_HienThi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/show_22.png"))); // NOI18N
        B_HienThi1.setText("Hiển Thị Thông Tin");
        B_HienThi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HienThi1ActionPerformed(evt);
            }
        });
        jPanel1.add(B_HienThi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 200, 40));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel29.setText("Ngày");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel30.setText("Năm");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 480, 20));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel31.setText("Tháng");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        N_Ngay.setMinimum(1);
        N_Ngay.setMinimumSize(new java.awt.Dimension(30, 20));
        N_Ngay.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel1.add(N_Ngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 50, 25));

        N_Thang.setMinimumSize(new java.awt.Dimension(30, 20));
        N_Thang.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel1.add(N_Thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 50, 25));

        N_Nam.setMinimumSize(new java.awt.Dimension(30, 20));
        N_Nam.setPreferredSize(new java.awt.Dimension(30, 20));
        N_Nam.setValue(1);
        jPanel1.add(N_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 60, 25));

        L_GiaSV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        L_GiaSV.setForeground(new java.awt.Color(204, 51, 255));
        L_GiaSV.setText("Gia");
        jPanel1.add(L_GiaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 25));

        L_SLSV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        L_SLSV.setForeground(new java.awt.Color(204, 51, 255));
        L_SLSV.setText("SL");
        jPanel1.add(L_SLSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 60, 25));

        L_TKSV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        L_TKSV.setForeground(new java.awt.Color(204, 51, 255));
        L_TKSV.setText("ST");
        jPanel1.add(L_TKSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 25));

        L_GiaTh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        L_GiaTh.setForeground(new java.awt.Color(51, 51, 255));
        L_GiaTh.setText("Gia");
        jPanel1.add(L_GiaTh, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 60, 25));

        L_SLT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        L_SLT.setForeground(new java.awt.Color(51, 51, 255));
        L_SLT.setText("SL");
        jPanel1.add(L_SLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 60, 25));

        L_TKT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        L_TKT.setForeground(new java.awt.Color(51, 51, 255));
        L_TKT.setText("ST");
        jPanel1.add(L_TKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 60, 25));

        Tong.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Tong.setText("Gia");
        jPanel1.add(Tong, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 120, 30));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Do_an/img/bg_vexe2.jpg"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TongKetVe tk = new TongKetVe();
        tk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void B_HienThi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HienThi1ActionPerformed
        // TODO add your handling code here:
        SinhVien();
        Thuong();
        Tong();
    }//GEN-LAST:event_B_HienThi1ActionPerformed

    public void SinhVien() {
        String loai = "SINHVIEN";
        String ngay = N_Nam.getValue() + "-" + N_Thang.getValue() + "-" + N_Ngay.getValue();
        L_GiaSV.setText(layGiaVe(loai));
        L_SLSV.setText(laysoluong("1", ngay));
        String Gia = layGiaVe(loai);
        int a = Integer.parseInt(Gia);
        int b = Integer.parseInt(laysoluong("1", ngay));
        L_TKSV.setText("" + a * b);

    }

    public void Thuong() {
        String loai = "KHACH";
        String Maloai = "2";
        String ngay = N_Nam.getValue() + "-" + N_Thang.getValue() + "-" + N_Ngay.getValue();
        L_GiaTh.setText(layGiaVe(loai));
        L_SLT.setText(laysoluong(Maloai, ngay));
        String Gia = layGiaVe(loai);
        int a = Integer.parseInt(Gia);
        int b = Integer.parseInt(laysoluong(Maloai, ngay));
        L_TKT.setText("" + a * b);

    }

    public void Tong() {
        int sv = Integer.parseInt(L_TKSV.getText());
        int thuong = Integer.parseInt(L_TKT.getText());
        int tongket = (sv + thuong);
        Tong.setText("" + tongket);
    }

    public String layMaLoaiVe(String Loai) {
        String MaLoaiVe = "";
        Connection kn = layKetNoi();
        String sql = "Select * from LOAIVE";
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                if (rs.getString("LoaiVe").equals(Loai)) {
                    MaLoaiVe = rs.getString("MaLoaiVe");
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(TongKetVeNgay.class.getName()).log(Level.SEVERE, null, e);
        }

        return MaLoaiVe;
    }

    public String layGiaVe(String Loai) {
        String LoaiVe = "";
        Connection kn = layKetNoi();
        String sql = "Select * from LOAIVE";
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                if (rs.getString("LoaiVe").equals(Loai)) {
                    LoaiVe = rs.getString("Giave");
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(TongKetVeNgay.class.getName()).log(Level.SEVERE, null, e);
        }

        return LoaiVe;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TongKetVeNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TongKetVeNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TongKetVeNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TongKetVeNgay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TongKetVeNgay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_HienThi1;
    private javax.swing.JLabel L_GiaSV;
    private javax.swing.JLabel L_GiaTh;
    private javax.swing.JLabel L_SLSV;
    private javax.swing.JLabel L_SLT;
    private javax.swing.JLabel L_TKSV;
    private javax.swing.JLabel L_TKT;
    private com.toedter.components.JSpinField N_Nam;
    private com.toedter.components.JSpinField N_Ngay;
    private com.toedter.components.JSpinField N_Thang;
    private javax.swing.JLabel Tong;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
